//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FcukWinforms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=Peover;uid=thomasr;pwd=thomasr")]
        public string ConnectionPeover {
            get {
                return ((string)(this["ConnectionPeover"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=FcukLonda;uid=itstaff01;pwd=monday1")]
        public string ConnectionLonda {
            get {
                return ((string)(this["ConnectionLonda"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vmsqldev\\sql2014;Initial Catalog=FcukIntegration;Integrated Security=" +
            "True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string FcukIntegrationConnectionString {
            get {
                return ((string)(this["FcukIntegrationConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vmsqldev\\sql2014;Initial Catalog=FcukIntegration;Integrated Security=" +
            "True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string FcukIntegrationConnectionStringLIFE_user {
            get {
                return ((string)(this["FcukIntegrationConnectionStringLIFE_user"]));
            }
            set {
                this["FcukIntegrationConnectionStringLIFE_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UKCAMVZLND01\\SQLEXPRESS;Initial Catalog=FcukIntegration;Integrated Se" +
            "curity=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string FcukIntegrationConnectionStringFCUK_user {
            get {
                return ((string)(this["FcukIntegrationConnectionStringFCUK_user"]));
            }
            set {
                this["FcukIntegrationConnectionStringFCUK_user"] = value;
            }
        }
    }
}
